#!/usr/bin/env python3
"""
claim_keyword_extractor.py — LLM-based keyword generation for citation verification (Stage 2).

Given a Chinese claim sentence and an English research quote, uses LLM (via openclaw)
to generate English keywords that BOTH reflect the claim's assertions AND are likely
to appear verbatim on the English-language source webpage.

Usage:
    python3 claim_keyword_extractor.py <claim_text> <research_quote> [--max-keywords 5]

Output (stdout):
    JSON array of keyword objects:
    [
      {"text": "design for recyclability", "source": "claim"},
      {"text": "forward reverse logistics", "source": "claim"},
      {"text": "re-use and recycling", "source": "research"}
    ]

Rules:
  - "source": "claim"  = derived from Chinese claim translation
  - "source": "research" = found verbatim in English research quote
  - Max 5 keywords total, at least 2 from claim
  - Each keyword 2-5 English words, no standalone prepositions
  - Prefer keywords likely to exist as exact substrings on source page

Exit codes:
  0  — Success (keywords may be empty on fallback)
  1  — Fatal error (LLM unavailable, I/O error)
"""

import json
import re
import subprocess
import sys
import argparse

# Timeout for LLM call (seconds)
LLM_TIMEOUT = 60

# Regex to find English-looking multi-word fragments in Chinese text
ENGLISH_PHRASE_RE = re.compile(r'\b[A-Za-z-]{3,}(?:\s+(?:and\s+)?[A-Za-z-]{3,}){1,3}')


def extract_keywords(claim: str, quote: str, max_keywords: int = 5) -> list[dict]:
    """Call LLM to generate claim-driven English keywords.

    Falls back to simple n-gram extraction when LLM is unavailable.
    """
    prompt = _build_prompt(claim, quote, max_keywords)
    llm_result = _call_llm(prompt)

    if llm_result is not None:
        validated = _validate_llm_output(llm_result, max_keywords)
        if validated:
            return _enforce_min_claim_source(validated)[:max_keywords]

    # LLM failed — attempt fallback extraction
    fallback = _fallback_extract(claim, quote, max_keywords)
    return fallback[:max_keywords]


def _build_prompt(claim: str, quote: str, max_keywords: int) -> str:
    """Build the LLM prompt for keyword extraction."""
    return (
        'You are a keyword extraction assistant for academic citation verification.\n\n'
        f'Chinese Claim (factual assertion): {claim}\n\n'
        f'English Research Quote (from source webpage): {quote}\n\n'
        'Generate English keywords for verifying whether the source webpage supports '
        'the Chinese claim. Each keyword must BOTH reflect the claim\'s assertions AND '
        'be likely to appear verbatim on the source webpage.\n\n'
        'RULES:\n'
        f'1. Output at most {max_keywords} keyword objects as a JSON array.\n'
        '2. Each keyword must be 2-5 English words (short multi-word phrases).\n'
        '3. At least 2 keywords must have "source": "claim".\n'
        '4. Keywords with "source": "claim" are generated by translating the Chinese '
        'claim into concise English phrases a webpage would use.\n'
        '5. Keywords with "source": "research" must appear as exact or near-exact '
        'substrings in the English research quote.\n'
        '6. Avoid prepositions ("of", "in", "for", "on", "at", "to", "with") as '
        'standalone keyword components. Every word must carry semantic weight.\n'
        '7. Output valid JSON only — no markdown, no code fences, no commentary.\n\n'
        'Example:\n'
        '[\n'
        '  {"text": "closed-loop supply chain", "source": "claim"},\n'
        '  {"text": "forward reverse logistics", "source": "claim"},\n'
        '  {"text": "re-use and recycling", "source": "research"}\n'
        ']'
    )


def _call_llm(prompt: str) -> list | None:
    """Execute openclaw infer model run and return parsed output, or None on failure."""
    try:
        proc = subprocess.run(
            ['openclaw', 'infer', 'model', 'run', '--prompt', prompt, '--json'],
            capture_output=True, text=True, timeout=LLM_TIMEOUT,
        )
        if proc.returncode != 0:
            print(f"LLM process exited {proc.returncode}: {proc.stderr.strip()}",
                  file=sys.stderr)
            return None

        result = json.loads(proc.stdout)
        outputs = result.get('outputs', [])
        if not outputs:
            print("LLM returned empty outputs", file=sys.stderr)
            return None

        raw = outputs[0].get('text', '').strip()
        # Strip optional markdown fences
        raw = re.sub(r'^```(?:json)?\s*\n?', '', raw)
        raw = re.sub(r'\n?```\s*$', '', raw)
        return json.loads(raw)

    except subprocess.TimeoutExpired:
        print("LLM call timed out", file=sys.stderr)
    except json.JSONDecodeError as e:
        print(f"LLM response is not valid JSON: {e}", file=sys.stderr)
    except FileNotFoundError:
        print("'openclaw' binary not found in PATH", file=sys.stderr)
    except Exception as e:
        print(f"LLM call failed: {e}", file=sys.stderr)

    return None


def _validate_llm_output(data: list, max_keywords: int) -> list[dict]:
    """Validate and clean LLM output into keyword objects."""
    if not isinstance(data, list):
        print("LLM output is not a list", file=sys.stderr)
        return []

    validated = []
    for item in data:
        if not isinstance(item, dict):
            continue
        text = (item.get('text') or '').strip()
        source = (item.get('source') or '').strip().lower()
        if not text or source not in ('claim', 'research'):
            continue
        word_count = len(text.split())
        if word_count < 2 or word_count > 5:
            continue
        validated.append({'text': text, 'source': source})

    return validated[:max_keywords]


def _enforce_min_claim_source(keywords: list[dict], minimum: int = 2) -> list[dict]:
    """Ensure at least *minimum* keywords are tagged as 'claim'-source."""
    claim_count = sum(1 for k in keywords if k['source'] == 'claim')
    if claim_count >= minimum:
        return keywords

    # Promote research keywords that semantically overlap with claim
    for kw in keywords:
        if kw['source'] == 'research' and claim_count < minimum:
            kw['source'] = 'claim'
            claim_count += 1

    return keywords


def _fallback_extract(claim: str, quote: str, max_keywords: int = 5) -> list[dict]:
    """Simple fallback: extract English phrases from claim quote as keywords."""
    seen = set()
    keywords = []

    # 1. Extract capitalized / multi-word phrases from research quote
    for m in ENGLISH_PHRASE_RE.finditer(quote):
        phrase = m.group(0).strip().lower()
        if phrase not in seen and len(phrase.split()) >= 2:
            seen.add(phrase)
            keywords.append({'text': phrase, 'source': 'research'})

    # 2. Extract English-like phrases embedded in Chinese claim
    for m in ENGLISH_PHRASE_RE.finditer(claim):
        phrase = m.group(0).strip().lower()
        if phrase not in seen and len(phrase.split()) >= 2:
            seen.add(phrase)
            keywords.append({'text': phrase, 'source': 'claim'})

    # 3. Ensure at least 2 claim-sourced
    if sum(1 for k in keywords if k['source'] == 'claim') < 2:
        for kw in keywords:
            if kw['source'] != 'claim' and sum(1 for k in keywords if k['source'] == 'claim') < 2:
                kw['source'] = 'claim'

    return keywords[:max_keywords]


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Generate claim-driven English keywords for citation verification',
    )
    parser.add_argument('claim_text', help='Chinese claim sentence with footnote')
    parser.add_argument('research_quote', help='English quote from research source')
    parser.add_argument(
        '--max-keywords', type=int, default=5,
        help='Maximum keywords to generate (default: 5)',
    )

    args = parser.parse_args()

    if not args.claim_text.strip():
        print('Error: claim_text cannot be empty', file=sys.stderr)
        sys.exit(1)
    if not args.research_quote.strip():
        print('Error: research_quote cannot be empty', file=sys.stderr)
        sys.exit(1)

    keywords = extract_keywords(args.claim_text, args.research_quote, args.max_keywords)
    print(json.dumps(keywords, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
